### Constructores de matrices

NumPy provee diversas funciones para crear matrices , algunas de las cuales ya vimos cuando estudiamos vectores , la diferencia consiste en que ahora ya no usamos un número para indicar el tamaño de un vector, si no una **tupla** de 2 elementos: (m,n) . Algunas de las funciones  que aplican tanto a vectores como a matrices son:

* np.array: crear una matriz a partir de una lista de listas: cada fila es una sublista
* np.zeros: crear una matriz de ceros
* np.ones: crear una matriz de unos
* np.empty: crear una matriz sin importarnos sus valores
* np.full: crear una matriz  con cierto valor
* np.copy: crea un clon o copia de cierta matriz

Algunas funciones específicas de matrices son:

* np.matrix: resultado casi identico a la función mas general np.array ,pero posee algunas propiedades adicionales específicas de listas, por ejemplo notación sencilla para inversas de matrices.
* np.eye: crear una matriz con 1s en su diagonal principal y ceros en el resto
* np.identity : crear una matriz identidad

Algunas funciones que solo aplican a vectores y no a matrices son:

* np.arange
* np.linspace

Existen otras pero estas son posiblemente las mas comunes. Puedes consultar las otras disponibles en: https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

**Ejercicio**: Investigar y ejemplificar diferencias entre np.array y np.matrix

# np.array

numpy.array crea un array. Estructuras de datos en Python pueden convertirse en arrays por medio de esta función. El dtype por default es float64.

Esta función se usa para crear un array con un tipo de dato y lista de valores especificados en sus argumentos.

In [5]:
a = np.array(2, dtype = int)
print(a)

2


In [6]:
np.array((2,3,5), dtype = int)

array([2, 3, 5])

In [7]:
np.array((2,3,5), dtype = float)

array([2., 3., 5.])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
type(np.zeros(5))

numpy.ndarray

# np.matrix

Esta clase retorna una matriz de una cadena de datos o de un objeto array. La matriz obtenida es un array en 2D.
Esta función necesita  los siguientes parámetros:

data: se requiere un array o string
dtype: el tipo de dato a regresar es un array

Se retorna un objeto como una matriz.

Una matriz es un array especializado 2D que mantiene su naturaleza 2D a través de las operaciones. Tiene ciertos operadores especiales, como la multiplicación matricial ("*") y potencia de matrices ("**").

In [10]:
np.matrix('1 2; 3 4') 

matrix([[1, 2],
        [3, 4]])

In [13]:
np.matrix([[5, 6, 7], [4, 6]])

matrix([[list([5, 6, 7]), list([4, 6])]], dtype=object)

## Diferencias

* Una de las diferencias importantes entre np.array y np.matrix es que matrix es para estrictamente 2 dimensiones, mientras que array es N-dimensional. 

* Los objetos matrix son una subclase delos ndrray, así que heredan todos los atributos y métodos de los ndarray.

* Una de las mayores ventajas de np.matrix es que proveen una notación conveniente para multiplicación de matrices.

* numpy arrays siguen la regla de que las operaciones son aplicadas por elemento

* La principal ventaja de np.array sobre np.matrix es que los array son más generales que las matrices en 2 dimensiones.

In [16]:
x = np.matrix('4 3; 2 1')
y = np.matrix('1 2; 3 4')

print(x)
print(y)

[[4 3]
 [2 1]]
[[1 2]
 [3 4]]


In [17]:
x*y

matrix([[13, 20],
        [ 5,  8]])

Si fueran arrays el resultado sería el siguiente:

In [19]:
p = np.array([[4, 3], [2, 1]])
q = np.array([[1, 2], [3, 4]])

print(p)
print(q)

[[4 3]
 [2 1]]
[[1 2]
 [3 4]]


In [20]:
p*q

array([[4, 6],
       [6, 4]])

Sin embargo, en Python 3.5 se incluye el operador "@" con el que se logra el mismo resultado de multiplicación matricial, o bien por medio del producto punto:

In [21]:
p@q

array([[13, 20],
       [ 5,  8]])

In [22]:
np.dot(p,q)

array([[13, 20],
       [ 5,  8]])

Tanto matrix como arrays tienen .T para transpose, pero matriz tiene .H para conjugate transpose, y .I para la inversa

In [31]:
print(p.T)

print(x.T)

print(x.H)

print(x.I)

[[4 2]
 [3 1]]
[[4 2]
 [3 1]]
[[4 2]
 [3 1]]
[[-0.5  1.5]
 [ 1.  -2. ]]


El operador ** también se comporta diferente.

En una matriz el resultado es la multiplicación matricial de esa matriz por si misma (a * a). Mientras que en un array el resultado es otro array donde cada uno de sus elementos se elevaron al cuadrado.

In [33]:
print(x)  # matriz

print(x**2)

[[4 3]
 [2 1]]
[[22 15]
 [10  7]]


In [34]:
print(p) # array

print(p**2)

[[4 3]
 [2 1]]
[[16  9]
 [ 4  1]]


**Ejercicio aplicado en DS**
Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion neural_network(X) para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Utilizando multiplicacion de matrices se debe calcular para cada fila de la matriz de entrada X el valor de las neuronas de la capa intermedia, esto producira una nueva matriz con el mismo numero de filas que X y 2 columnas(1 para cada neurona) , a  los valores de esta matriz se les debe aplicar la funcion "sigmoid"(descrita a continuacion) para limitarlos al intervalo de 0 a 1, esto produce una matriz del mismo tamanio pero con valores entre 0 a 1, esta matriz se multiplica matricialmente por la matriz que representa los pesos de la capa de salida  y este proceso produce un nuevo tensor al cual se debe aplicar nuevamente la funcion sigmoid. El resultado debe ser un tensor con el mismo numero de filas que la matriz X y una sola columna(una prediccion para cada fila de X

<img src="https://cdn-images-1.medium.com/max/1600/1*Xu7B5y9gp0iL5ooBj7LtWw.png">

In [8]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    
    return 1/(1+np.exp(-x))

In [9]:
H1_W = np.array([[0.25,-8],
                 [0.37,14]])
OL_W = np.array([[4],[9]])

X =  np.array([[0.1,0.2],
               [1,2]])

H1 = np.matmul(X,H1_W)
H1 = sigmoid(H1)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1
OL = np.matmul(H1,OL_W)
OL = sigmoid(OL)  # funcion de activacion: convertir a valores en el intervalo de 0 a 1


print(OL)

[[0.99995577]
 [0.99999332]]


In [1]:
import numpy as np

def neural_network(x):
    
    HL1 = np.array([0.25,0.37])
    HL2 = np.array([-8,14])
    OL = np.array([4, 9])
    
    n1 = np.dot(x, HL1)
    n2 = np.dot(x, HL2)
    
    HL = np.array([n1, n2])
    
    resultado = np.dot(HL, OL)
    
    return resultado